domain: example.com
url: https://example.com

title: Hello Veda Guidance
email: Hellovedaguidance@outlook.com
author: Navedia-Young

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
rrss:
  
  #instagram: Hola
  linkedin: https://www.linkedin.com/in/navedia-young-a5a46920/
  # whatsapp: 123
  email: Hellovedaguidance@outlook.com
